# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'QY_Tips' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~> 3.1.0'
  # Pods for QY_Tips
   pod 'SDWebImage', '~> 3.8.2’
   pod 'SVProgressHUD', '~> 2.0.3'
   pod 'FMDB', '~> 2.6.2'
end








